version: "3.9"

services:
api:
build:
context: .
dockerfile: Dockerfile
container_name: phantompulse-api
restart: unless-stopped
ports:
- "5000:8080"
environment:
ASPNETCORE_ENVIRONMENT: Development

```
  ConnectionStrings__Default: Host=postgres;Database=phantompulse;Username=postgres;Password=sql@123

  Auth__Secret: IhzybZDvbuuvF+XP+sE4OZ+sNIJTCrrLrGqGIzM3sDdLXF/THNFqJirzk5Q=
  Auth__Issuer: phantompulse
  Auth__Audience: phantompulse-api

  WhatsApp__PhoneNumberId: ""
  WhatsApp__AccessToken: ""
  WhatsApp__WebhookVerifyToken: ""

depends_on:
  - postgres
```

postgres:
image: postgres:17
container_name: phantompulse-postgres
restart: unless-stopped
environment:
POSTGRES_DB: phantompulse
POSTGRES_USER: postgres
POSTGRES_PASSWORD: sql@123
ports:
- "5432:5432"
volumes:
- ./postgres-data:/var/lib/postgresql/data
