// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhantomPulse.Infrastructure.Persistence;

#nullable disable

namespace PhantomPulse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608150458_AddMessageTemplates")]
    partial class AddMessageTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhantomPulse.Automation.Entities.ChatbotSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentNode")
                        .HasColumnType("integer")
                        .HasColumnName("current_node");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("WaPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wa_phone_number");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_chatbot_sessions");

                    b.ToTable("chatbot_sessions", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Automation.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Campaigns.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Crm.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Crm.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_deals_contact_id");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_slug");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View dashboard",
                            Key = "dashboard.view",
                            Module = "dashboard"
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View users",
                            Key = "users.view",
                            Module = "users"
                        },
                        new
                        {
                            Id = new Guid("00000002-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create users",
                            Key = "users.create",
                            Module = "users"
                        },
                        new
                        {
                            Id = new Guid("00000002-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit users",
                            Key = "users.edit",
                            Module = "users"
                        },
                        new
                        {
                            Id = new Guid("00000002-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete users",
                            Key = "users.delete",
                            Module = "users"
                        },
                        new
                        {
                            Id = new Guid("00000003-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View contacts",
                            Key = "contacts.view",
                            Module = "contacts"
                        },
                        new
                        {
                            Id = new Guid("00000003-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create contacts",
                            Key = "contacts.create",
                            Module = "contacts"
                        },
                        new
                        {
                            Id = new Guid("00000003-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit contacts",
                            Key = "contacts.edit",
                            Module = "contacts"
                        },
                        new
                        {
                            Id = new Guid("00000003-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete contacts",
                            Key = "contacts.delete",
                            Module = "contacts"
                        },
                        new
                        {
                            Id = new Guid("00000004-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View conversations",
                            Key = "conversations.view",
                            Module = "conversations"
                        },
                        new
                        {
                            Id = new Guid("00000004-0007-0000-0000-000000000000"),
                            Action = "reply",
                            Description = "Reply to conversations",
                            Key = "conversations.reply",
                            Module = "conversations"
                        },
                        new
                        {
                            Id = new Guid("00000005-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View telephony",
                            Key = "telephony.view",
                            Module = "telephony"
                        },
                        new
                        {
                            Id = new Guid("00000005-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Make calls",
                            Key = "telephony.create",
                            Module = "telephony"
                        },
                        new
                        {
                            Id = new Guid("00000005-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit telephony settings",
                            Key = "telephony.edit",
                            Module = "telephony"
                        },
                        new
                        {
                            Id = new Guid("00000005-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete call records",
                            Key = "telephony.delete",
                            Module = "telephony"
                        },
                        new
                        {
                            Id = new Guid("00000006-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View lead pipeline",
                            Key = "leadmanagement.view",
                            Module = "leadmanagement"
                        },
                        new
                        {
                            Id = new Guid("00000006-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create leads/deals",
                            Key = "leadmanagement.create",
                            Module = "leadmanagement"
                        },
                        new
                        {
                            Id = new Guid("00000006-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit leads/deals",
                            Key = "leadmanagement.edit",
                            Module = "leadmanagement"
                        },
                        new
                        {
                            Id = new Guid("00000006-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete leads/deals",
                            Key = "leadmanagement.delete",
                            Module = "leadmanagement"
                        },
                        new
                        {
                            Id = new Guid("00000007-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View calendars",
                            Key = "calendars.view",
                            Module = "calendars"
                        },
                        new
                        {
                            Id = new Guid("00000007-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create calendar events",
                            Key = "calendars.create",
                            Module = "calendars"
                        },
                        new
                        {
                            Id = new Guid("00000007-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit calendar events",
                            Key = "calendars.edit",
                            Module = "calendars"
                        },
                        new
                        {
                            Id = new Guid("00000007-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete calendar events",
                            Key = "calendars.delete",
                            Module = "calendars"
                        },
                        new
                        {
                            Id = new Guid("00000008-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View marketing campaigns",
                            Key = "marketing.view",
                            Module = "marketing"
                        },
                        new
                        {
                            Id = new Guid("00000008-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create campaigns",
                            Key = "marketing.create",
                            Module = "marketing"
                        },
                        new
                        {
                            Id = new Guid("00000008-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit campaigns",
                            Key = "marketing.edit",
                            Module = "marketing"
                        },
                        new
                        {
                            Id = new Guid("00000008-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete campaigns",
                            Key = "marketing.delete",
                            Module = "marketing"
                        },
                        new
                        {
                            Id = new Guid("00000009-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View automations",
                            Key = "automation.view",
                            Module = "automation"
                        },
                        new
                        {
                            Id = new Guid("00000009-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create automations",
                            Key = "automation.create",
                            Module = "automation"
                        },
                        new
                        {
                            Id = new Guid("00000009-0006-0000-0000-000000000000"),
                            Action = "execute",
                            Description = "Execute automations",
                            Key = "automation.execute",
                            Module = "automation"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View AI agents",
                            Key = "aiagents.view",
                            Module = "aiagents"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create AI agents",
                            Key = "aiagents.create",
                            Module = "aiagents"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit AI agents",
                            Key = "aiagents.edit",
                            Module = "aiagents"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete AI agents",
                            Key = "aiagents.delete",
                            Module = "aiagents"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View templates",
                            Key = "templates.view",
                            Module = "templates"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create templates",
                            Key = "templates.create",
                            Module = "templates"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit templates",
                            Key = "templates.edit",
                            Module = "templates"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete templates",
                            Key = "templates.delete",
                            Module = "templates"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View social planner",
                            Key = "social.view",
                            Module = "social"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0002-0000-0000-000000000000"),
                            Action = "create",
                            Description = "Create social posts",
                            Key = "social.create",
                            Module = "social"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0003-0000-0000-000000000000"),
                            Action = "edit",
                            Description = "Edit social posts",
                            Key = "social.edit",
                            Module = "social"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0004-0000-0000-000000000000"),
                            Action = "delete",
                            Description = "Delete social posts",
                            Key = "social.delete",
                            Module = "social"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View reputation",
                            Key = "reputation.view",
                            Module = "reputation"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0005-0000-0000-000000000000"),
                            Action = "manage",
                            Description = "Manage reviews & reputation",
                            Key = "reputation.manage",
                            Module = "reputation"
                        },
                        new
                        {
                            Id = new Guid("0000000e-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View reports",
                            Key = "reporting.view",
                            Module = "reporting"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0001-0000-0000-000000000000"),
                            Action = "view",
                            Description = "View settings",
                            Key = "settings.view",
                            Module = "settings"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0005-0000-0000-000000000000"),
                            Action = "manage",
                            Description = "Manage settings",
                            Key = "settings.manage",
                            Module = "settings"
                        });
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<string>("SystemRoleType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("system_role_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_name");

                    b.HasIndex("TenantId", "SystemRoleType")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_tenant_id_system_role_type")
                        .HasFilter("is_system = true AND system_role_type IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.SubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sub_accounts");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_sub_accounts_agency_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_accounts_slug");

                    b.ToTable("sub_accounts", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SubAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_account_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("agency_id IS NULL");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("SubAccountId")
                        .HasDatabaseName("ix_users_sub_account_id");

                    b.HasIndex("AgencyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_agency_id_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_scope_consistency", "(scope = 'Platform'   AND agency_id IS NULL     AND sub_account_id IS NULL) OR (scope = 'Agency'     AND agency_id IS NOT NULL AND sub_account_id IS NULL) OR (scope = 'SubAccount' AND agency_id IS NOT NULL AND sub_account_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PhantomPulse.Messaging.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("WaPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wa_phone_number");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Messaging.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Messaging.Entities.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Usage")
                        .HasColumnType("integer")
                        .HasColumnName("usage");

                    b.PrimitiveCollection<string[]>("Variables")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("variables");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("PhantomPulse.Crm.Entities.Deal", b =>
                {
                    b.HasOne("PhantomPulse.Crm.Entities.Contact", "Contact")
                        .WithMany("Deals")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deals_contacts_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.RefreshToken", b =>
                {
                    b.HasOne("PhantomPulse.Foundation.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.RolePermission", b =>
                {
                    b.HasOne("PhantomPulse.Foundation.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("PhantomPulse.Foundation.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.SubAccount", b =>
                {
                    b.HasOne("PhantomPulse.Foundation.Entities.Agency", "Agency")
                        .WithMany("SubAccounts")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sub_accounts_agencies_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.User", b =>
                {
                    b.HasOne("PhantomPulse.Foundation.Entities.Agency", "Agency")
                        .WithMany("Users")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_agencies_agency_id");

                    b.HasOne("PhantomPulse.Foundation.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_roles_role_id");

                    b.HasOne("PhantomPulse.Foundation.Entities.SubAccount", "SubAccount")
                        .WithMany("Users")
                        .HasForeignKey("SubAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_sub_accounts_sub_account_id");

                    b.Navigation("Agency");

                    b.Navigation("Role");

                    b.Navigation("SubAccount");
                });

            modelBuilder.Entity("PhantomPulse.Messaging.Entities.Message", b =>
                {
                    b.HasOne("PhantomPulse.Messaging.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PhantomPulse.Crm.Entities.Contact", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Agency", b =>
                {
                    b.Navigation("SubAccounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.SubAccount", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhantomPulse.Foundation.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PhantomPulse.Messaging.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
